"""
Voice Extraction FastAPI Service
Extracts audio from video files, then separates vocals using Meta's Demucs.

Run in the 'dm' conda environment on port 8002:
    conda activate dm
    pip install fastapi uvicorn python-multipart demucs soundfile
    uvicorn extract_voice_service:app --host 0.0.0.0 --port 8002
"""

import subprocess
import sys
import shutil
import tempfile
import uuid
from pathlib import Path

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import Response

app = FastAPI(title="Voice Extraction Service")

VIDEO_EXTENSIONS = {".mp4", ".mkv", ".avi", ".mov", ".webm", ".flv", ".wmv"}
AUDIO_EXTENSIONS = {".wav", ".mp3", ".flac", ".ogg", ".m4a", ".aac", ".wma"}


def check_ffmpeg() -> bool:
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


@app.get("/health")
def health():
    return {"status": "ok", "ffmpeg": check_ffmpeg()}


@app.post("/extract")
async def extract_voice(file: UploadFile = File(...), model: str = "htdemucs"):
    """
    Accept an audio/video file upload, extract vocals using Demucs.
    Returns the vocals WAV file as bytes.
    """
    if model not in ("htdemucs", "htdemucs_ft", "mdx_extra"):
        raise HTTPException(400, f"Invalid model: {model}. Use htdemucs, htdemucs_ft, or mdx_extra")

    if not check_ffmpeg():
        raise HTTPException(500, "ffmpeg is not installed on the server")

    job_id = str(uuid.uuid4())[:8]
    work_dir = Path(tempfile.mkdtemp(prefix=f"extract_{job_id}_"))

    try:
        # Save uploaded file
        suffix = Path(file.filename).suffix.lower() if file.filename else ".wav"
        input_path = work_dir / f"input{suffix}"
        content = await file.read()
        input_path.write_bytes(content)

        # If video, extract audio track first
        if suffix in VIDEO_EXTENSIONS:
            audio_path = work_dir / "extracted_audio.wav"
            cmd = [
                "ffmpeg", "-y", "-i", str(input_path),
                "-vn", "-acodec", "pcm_s16le",
                "-ar", "44100", "-ac", "2",
                str(audio_path),
            ]
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                raise HTTPException(500, f"ffmpeg error: {result.stderr[:500]}")
        elif suffix in AUDIO_EXTENSIONS:
            # Convert to WAV if not already
            if suffix != ".wav":
                audio_path = work_dir / "converted_audio.wav"
                cmd = [
                    "ffmpeg", "-y", "-i", str(input_path),
                    "-acodec", "pcm_s16le", "-ar", "44100", "-ac", "2",
                    str(audio_path),
                ]
                result = subprocess.run(cmd, capture_output=True, text=True)
                if result.returncode != 0:
                    raise HTTPException(500, f"ffmpeg conversion error: {result.stderr[:500]}")
            else:
                audio_path = input_path
        else:
            raise HTTPException(400, f"Unsupported file format: {suffix}")

        # Run Demucs for vocal separation
        output_dir = work_dir / "demucs_out"
        cmd = [
            sys.executable, "-m", "demucs",
            "--two-stems", "vocals",
            "-n", model,
            "-o", str(output_dir),
            str(audio_path),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
        if result.returncode != 0:
            raise HTTPException(500, f"Demucs error: {result.stderr[:500]}")

        # Locate vocals file
        vocals_path = output_dir / model / audio_path.stem / "vocals.wav"
        if not vocals_path.exists():
            raise HTTPException(500, "Vocals file was not generated by Demucs")

        # Read vocals into memory and return
        vocals_bytes = vocals_path.read_bytes()
        return Response(content=vocals_bytes, media_type="audio/wav")

    except HTTPException:
        raise
    except subprocess.TimeoutExpired:
        raise HTTPException(504, "Processing timed out (>1 hour)")
    except Exception as e:
        raise HTTPException(500, f"Unexpected error: {str(e)}")
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8002)
